Class {
	#name : #DrGeoScript174591904,
	#superclass : #DrGeoUserScript,
	#category : #'DrGeo-Model-Script'
}

{ #category : #public }
DrGeoScript174591904 class >> description [
	^'dfdf'
]

{ #category : #private }
DrGeoScript174591904 class >> newArgumentsType [
	^{DrGAngleItem.DrGArcItem}
]

{ #category : #public }
DrGeoScript174591904 class >> scriptName [
	^'Test'
]

{ #category : #public }
DrGeoScript174591904 >> compute [
"Edit me"
	^1+1
]
