Class {
	#name : #DrGeoScript161808832,
	#superclass : #DrGeoUserScript,
	#category : #'DrGeo-Model-Script'
}

{ #category : #public }
DrGeoScript161808832 class >> description [
	^'te'
]

{ #category : #private }
DrGeoScript161808832 class >> newArgumentsType [
	^{}
]

{ #category : #public }
DrGeoScript161808832 class >> scriptName [
	^'test pour faire une addition'
]

{ #category : #public }
DrGeoScript161808832 >> compute [
"Edit me"
	^1+3.5 / 0.5
]
